<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCuwVSPd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCuwVSPd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCuwVSPd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCuwVSPd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCuwVSPd\App_KernelDevDebugContainer([
    'container.build_hash' => 'CuwVSPd',
    'container.build_id' => '5a3e286a',
    'container.build_time' => 1653463925,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCuwVSPd');
