<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB28dpWx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB28dpWx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB28dpWx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB28dpWx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB28dpWx\App_KernelDevDebugContainer([
    'container.build_hash' => 'B28dpWx',
    'container.build_id' => 'cbae72bf',
    'container.build_time' => 1652473164,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB28dpWx');
