<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDdvxboi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDdvxboi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDdvxboi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDdvxboi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDdvxboi\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ddvxboi',
    'container.build_id' => 'a347f864',
    'container.build_time' => 1652621679,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDdvxboi');
