<?php

namespace ContainerTxIYy08;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImagenService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.buB0Xfs.App\Entity\Imagen' shared service.
     *
     * @return \App\Entity\Imagen
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.buB0Xfs": it references class "App\\Entity\\Imagen" but no such service exists.');
    }
}
