<?php

namespace ContainerNGFl7Gz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMusicalService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..oD9six.App\Entity\Musical' shared service.
     *
     * @return \App\Entity\Musical
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator..oD9six": it references class "App\\Entity\\Musical" but no such service exists.');
    }
}
