<?php

namespace ContainerCuwVSPd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1JxlpHDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1JxlpHD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1JxlpHD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'imagenRepository' => ['privates', 'App\\Repository\\ImagenRepository', 'getImagenRepositoryService', true],
        ], [
            'imagenRepository' => 'App\\Repository\\ImagenRepository',
        ]);
    }
}
