<?php

namespace Container5JxYxlo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForm_DropzoneService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'form.dropzone' shared service.
     *
     * @return \Symfony\UX\Dropzone\Form\DropzoneType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-dropzone/Form/DropzoneType.php';

        return $container->privates['form.dropzone'] = new \Symfony\UX\Dropzone\Form\DropzoneType();
    }
}
