<?php

namespace ContainerI3PzAdq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAudioService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.F04_Ow9.App\Entity\Audio' shared service.
     *
     * @return \App\Entity\Audio
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.F04_Ow9": it references class "App\\Entity\\Audio" but no such service exists.');
    }
}
