<?php

namespace ContainerWUK17u0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParticipante2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.pPSJa7S.App\Entity\Participante' shared service.
     *
     * @return \App\Entity\Participante
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.pPSJa7S": it references class "App\\Entity\\Participante" but no such service exists.');
    }
}
