<?php

namespace ContainerBxkX0QQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParticipanteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.fh89mcT.App\Entity\Participante' shared service.
     *
     * @return \App\Entity\Participante
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.fh89mcT": it references class "App\\Entity\\Participante" but no such service exists.');
    }
}
