<?php

namespace ContainerFemTmOM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Trpe8JrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Trpe8Jr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Trpe8Jr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'musicalRepository' => ['privates', 'App\\Repository\\MusicalRepository', 'getMusicalRepositoryService', true],
            'participante' => ['privates', '.errored..service_locator.Trpe8Jr.App\\Entity\\Participante', NULL, 'Cannot autowire service ".service_locator.Trpe8Jr": it references class "App\\Entity\\Participante" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'musicalRepository' => 'App\\Repository\\MusicalRepository',
            'participante' => 'App\\Entity\\Participante',
        ]);
    }
}
