<?php

namespace ContainerFemTmOM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Fh89mcTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fh89mcT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fh89mcT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'participante' => ['privates', '.errored..service_locator.fh89mcT.App\\Entity\\Participante', NULL, 'Cannot autowire service ".service_locator.fh89mcT": it references class "App\\Entity\\Participante" but no such service exists.'],
        ], [
            'participante' => 'App\\Entity\\Participante',
        ]);
    }
}
