<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Musical extends \App\Entity\Musical implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Musical' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Musical' . "\0" . 'Nombre', '' . "\0" . 'App\\Entity\\Musical' . "\0" . 'Sinopsis', '' . "\0" . 'App\\Entity\\Musical' . "\0" . 'Cartel', '' . "\0" . 'App\\Entity\\Musical' . "\0" . 'Anyo', '' . "\0" . 'App\\Entity\\Musical' . "\0" . 'Video', '' . "\0" . 'App\\Entity\\Musical' . "\0" . 'imagenes', '' . "\0" . 'App\\Entity\\Musical' . "\0" . 'audios', '' . "\0" . 'App\\Entity\\Musical' . "\0" . 'participantes'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Musical' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Musical' . "\0" . 'Nombre', '' . "\0" . 'App\\Entity\\Musical' . "\0" . 'Sinopsis', '' . "\0" . 'App\\Entity\\Musical' . "\0" . 'Cartel', '' . "\0" . 'App\\Entity\\Musical' . "\0" . 'Anyo', '' . "\0" . 'App\\Entity\\Musical' . "\0" . 'Video', '' . "\0" . 'App\\Entity\\Musical' . "\0" . 'imagenes', '' . "\0" . 'App\\Entity\\Musical' . "\0" . 'audios', '' . "\0" . 'App\\Entity\\Musical' . "\0" . 'participantes'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Musical $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre(string $Nombre): \App\Entity\Musical
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$Nombre]);

        return parent::setNombre($Nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getSinopsis(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSinopsis', []);

        return parent::getSinopsis();
    }

    /**
     * {@inheritDoc}
     */
    public function setSinopsis(string $Sinopsis): \App\Entity\Musical
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSinopsis', [$Sinopsis]);

        return parent::setSinopsis($Sinopsis);
    }

    /**
     * {@inheritDoc}
     */
    public function getCartel(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCartel', []);

        return parent::getCartel();
    }

    /**
     * {@inheritDoc}
     */
    public function setCartel(string $Cartel): \App\Entity\Musical
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCartel', [$Cartel]);

        return parent::setCartel($Cartel);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnyo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnyo', []);

        return parent::getAnyo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnyo(string $Anyo): \App\Entity\Musical
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnyo', [$Anyo]);

        return parent::setAnyo($Anyo);
    }

    /**
     * {@inheritDoc}
     */
    public function getVideo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVideo', []);

        return parent::getVideo();
    }

    /**
     * {@inheritDoc}
     */
    public function setVideo(?string $Video): \App\Entity\Musical
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVideo', [$Video]);

        return parent::setVideo($Video);
    }

    /**
     * {@inheritDoc}
     */
    public function getImagenes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagenes', []);

        return parent::getImagenes();
    }

    /**
     * {@inheritDoc}
     */
    public function addImagene(\App\Entity\Imagen $imagene): \App\Entity\Musical
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addImagene', [$imagene]);

        return parent::addImagene($imagene);
    }

    /**
     * {@inheritDoc}
     */
    public function removeImagene(\App\Entity\Imagen $imagene): \App\Entity\Musical
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeImagene', [$imagene]);

        return parent::removeImagene($imagene);
    }

    /**
     * {@inheritDoc}
     */
    public function getAudios(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAudios', []);

        return parent::getAudios();
    }

    /**
     * {@inheritDoc}
     */
    public function addAudio(\App\Entity\Audio $audio): \App\Entity\Musical
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAudio', [$audio]);

        return parent::addAudio($audio);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAudio(\App\Entity\Audio $audio): \App\Entity\Musical
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAudio', [$audio]);

        return parent::removeAudio($audio);
    }

    /**
     * {@inheritDoc}
     */
    public function getParticipantes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParticipantes', []);

        return parent::getParticipantes();
    }

    /**
     * {@inheritDoc}
     */
    public function addParticipante(\App\Entity\Participante $participante): \App\Entity\Musical
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addParticipante', [$participante]);

        return parent::addParticipante($participante);
    }

    /**
     * {@inheritDoc}
     */
    public function removeParticipante(\App\Entity\Participante $participante): \App\Entity\Musical
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeParticipante', [$participante]);

        return parent::removeParticipante($participante);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
